module.exports={
    HOST:"localhost",
    USER:"root",
    PASSWORD:"zicre573wef0",
    DB:'edocexpertisedb',
    dialect:"mysql",
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }};